// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOKWWE52NlYDaunIjFXfc2p11B-LSRYGg',
    appId: '1:477084726848:web:81250aaf486e2fd399d1a5',
    messagingSenderId: '477084726848',
    projectId: 'gocab-207bb',
    authDomain: 'gocab-207bb.firebaseapp.com',
    storageBucket: 'gocab-207bb.appspot.com',
    measurementId: 'G-8HJPREBZR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDep3xUispEWx8prvlEm0FYITO-iAJcRqA',
    appId: '1:477084726848:android:1c1e19c2546e06a299d1a5',
    messagingSenderId: '477084726848',
    projectId: 'gocab-207bb',
    storageBucket: 'gocab-207bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB2MIkyiRAWYXk5kCRGl2yGJaSSGREK5o',
    appId: '1:477084726848:ios:1e922ad11838e82f99d1a5',
    messagingSenderId: '477084726848',
    projectId: 'gocab-207bb',
    storageBucket: 'gocab-207bb.appspot.com',
    iosBundleId: 'com.example.gocab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB2MIkyiRAWYXk5kCRGl2yGJaSSGREK5o',
    appId: '1:477084726848:ios:1e922ad11838e82f99d1a5',
    messagingSenderId: '477084726848',
    projectId: 'gocab-207bb',
    storageBucket: 'gocab-207bb.appspot.com',
    iosBundleId: 'com.example.gocab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOKWWE52NlYDaunIjFXfc2p11B-LSRYGg',
    appId: '1:477084726848:web:8c287d0e72bde48799d1a5',
    messagingSenderId: '477084726848',
    projectId: 'gocab-207bb',
    authDomain: 'gocab-207bb.firebaseapp.com',
    storageBucket: 'gocab-207bb.appspot.com',
    measurementId: 'G-0W9HLVK7G8',
  );
}
